# Generated by Django 3.1.6 on 2021-02-12 22:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210212_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
