# Generated by Django 3.1.6 on 2021-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210213_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('E', 'economy'), ('P', 'politic'), ('S', 'sport'), ('T', 'tech')], max_length=1),
        ),
    ]
